#!/bin/bash

if ! [ -f "$1" ]; then
  echo "please specify the filename of the CSV. e.g.:"
  echo
  echo "./run file.csv"
  exit 1
fi

target_dir=$(dirname $1)
if [ "$target_dir" = "." ]; then
  target_dir=$PWD
fi
target_file=$(basename $1)

docker run -v "$target_dir":"$target_dir" -w "$target_dir" -it dbank-to-qif /app/convert $target_file
